# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.

# durations=0 will display all tests execution time, sorted in ascending order starting from from the slowest one.
# -vv will also display tests with durration = 0.00s
[pytest]
addopts = --verbose --pyargs --durations=0
markers =
    unit: marks unit test, i.e. testing a single, well isolated functionality (deselect with '-m "not unit"')
    train: tests related to train scripts (deselect with '-m "not train"')
    finetune: tests related to fine tune scripts (deselect with '-m "not finetune"')
    evaluate: tests related to fine tune scripts (deselect with '-m "not evaluate"')
    export: tests related to export to ONNX scripts (deselect with '-m "not export"')
    infer: tests related to inference scripts (deselect with '-m "not infer"')
    infer_onnx: tests related to ONNX-based inference scripts (deselect with '-m "not infer_onnx"')
    cv_unit: marks cv unit test (deselect with '-m "not cv_unit"')
    pointcloud_unit: marks point cloud unit test (deselect with '-m "not pointcloud_unit"')
    sdg_unit: marks sdg unit test (deselect with '-m "not sdg_unit"')
    tensorrt: marks tensorrt unit tests (deselect with '-m "not tensorrt"')
    ocrnet: marks ocrnet related unit tests
    ocdnet: marks ocdnet unit test (deselect with '-m "not ocdnet"')
    config: unit test for configs (deselect with '-m "not config"')
    schema_validation: unit test for schema validation (deselect with '-m "not schema_validation"')
